# default_pose_constants.py
# Defines default motor positions for Startup/Resting and Calibration poses.

STARTUP_POSE_NAME = "Startup/Resting"
CALIBRATION_POSE_NAME = "Calibration"

STARTUP_POSITIONS = {
    "turn_head_motor": 0,
    "tilt_forward_motor": 0,
    "upper_arm_left_rotation": 0,
    "elbow_left": 5500,
    "lower_arm_left_rotation": 0,
    "shoulder_vertical_left": -9000,
    "shoulder_horizontal_left": -9000,
    "upper_arm_right_rotation": 0,
    "elbow_right": 5500,
    "lower_arm_right_rotation": 0,
    "shoulder_vertical_right": -9000,
    "shoulder_horizontal_right": -9000,
    "thumb_right_opposition": -9000,
    "thumb_right_stretch": -9000,
    "index_right_stretch": -9000,
    "middle_right_stretch": -9000,
    "ring_right_stretch": -9000,
    "pinky_right_stretch": -9000,
    "thumb_left_opposition": -9000,
    "thumb_left_stretch": -9000,
    "index_left_stretch": -9000,
    "middle_left_stretch": -9000,
    "ring_left_stretch": -9000,
    "pinky_left_stretch": -9000,
    "wrist_left": 0,
    "wrist_right": 0,
}

CALIBRATION_POSITIONS = {
    "turn_head_motor": 0,
    "tilt_forward_motor": 0,
    "upper_arm_left_rotation": 0,
    "elbow_left": 0,
    "lower_arm_left_rotation": 0,
    "shoulder_vertical_left": 0,
    "shoulder_horizontal_left": 0,
    "upper_arm_right_rotation": 0,
    "elbow_right": 0,
    "lower_arm_right_rotation": 0,
    "shoulder_vertical_right": 0,
    "shoulder_horizontal_right": 0,
    "thumb_right_opposition": -9000,
    "thumb_right_stretch": -9000,
    "index_right_stretch": -9000,
    "middle_right_stretch": -9000,
    "ring_right_stretch": -9000,
    "pinky_right_stretch": -9000,
    "thumb_left_opposition": -9000,
    "thumb_left_stretch": -9000,
    "index_left_stretch": -9000,
    "middle_left_stretch": -9000,
    "ring_left_stretch": -9000,
    "pinky_left_stretch": -9000,
    "wrist_left": 0,
    "wrist_right": 0,
}
