string filepath # the (absolute) path to the audio file that should be played back
bool join # if this flag is set, the service call waits until auido has finished playing, before returning the result
---