string text # the textual input of the user
string description # the descrciption of the personality
---
string rest # the remaining textual llm-response, that has not been sent back as feedback
---
string sentence # an intermediate sentence, which was received from the llm