FROM ubuntu:jammy

RUN apt-get update && apt-get install -y curl gnupg
RUN curl -sSL https://download.tinkerforge.com/apt/$(. /etc/os-release; echo $ID)/tinkerforge.gpg | apt-key add - && \
    echo "deb https://download.tinkerforge.com/apt/$(. /etc/os-release; echo $ID $VERSION_CODENAME) main" > /etc/apt/sources.list.d/tinkerforge.list && \
    apt-get update --fix-missing && \
    apt-get install -y \
    brickd

CMD ["brickd"] 

# Expose the brickd port
EXPOSE 4223

