import * as Blockly from "blockly";

export const motor_blocks = Blockly.common.createBlockDefinitionsFromJsonArray([
    {
        type: "move_motor",
        message0: "move motor(s)  %1 %2 to %3 position from input %4",
        args0: [
            {
                type: "field_dropdown",
                name: "MOTORNAME",
                options: [
                    ["thumb left opposition", "THUMB_LEFT_OPPOSITION"],
                    ["thumb left stretch", "THUMB_LEFT_STRETCH"],
                    ["index finger left stretch", "INDEX_LEFT_STRETCH"],
                    ["middle finger left stretch", "MIDDLE_LEFT_STRETCH"],
                    ["ring finger left stretch", "RING_LEFT_STRETCH"],
                    ["pinky finger left stretch", "PINKY_LEFT_STRETCH"],
                    ["all fingers left", "ALL_FINGERS_LEFT_STRETCH"],
                    ["thumb right opposition", "THUMB_RIGHT_OPPOSITION"],
                    ["thumb right stretch", "THUMB_RIGHT_STRETCH"],
                    ["index finger right stretch", "INDEX_RIGHT_STRETCH"],
                    ["middle finger right stretch", "MIDDLE_RIGHT_STRETCH"],
                    ["ring finger right stretch", "RING_RIGHT_STRETCH"],
                    ["pinky finger right stretch", "PINKY_RIGHT_STRETCH"],
                    ["all fingers right", "ALL_FINGERS_RIGHT_STRETCH"],
                    ["upper left arm rotation", "UPPER_ARM_LEFT_ROTATION"],
                    ["elbow left", "ELBOW_LEFT"],
                    ["lower left arm rotation", "LOWER_ARM_LEFT_ROTATION"],
                    ["wrist left", "WRIST_LEFT"],
                    ["left shoulder vertical", "SHOULDER_VERTICAL_LEFT"],
                    ["left shoulder horizontal", "SHOULDER_HORIZONTAL_LEFT"],
                    ["upper right arm rotation", "UPPER_ARM_RIGHT_ROTATION"],
                    ["elbow right", "ELBOW_RIGHT"],
                    ["lower right arm rotation", "LOWER_ARM_RIGHT_ROTATION"],
                    ["wrist right", "WRIST_RIGHT"],
                    ["right shoulder vertical", "SHOULDER_VERTICAL_RIGHT"],
                    ["right shoulder horizontal", "SHOULDER_HORIZONTAL_RIGHT"],
                    ["tilt head forward", "TILT_FORWARD_HEAD"],
                    ["turn head", "TURN_HEAD"],
                ],
            },
            {
                type: "input_dummy",
            },
            {
                type: "field_dropdown",
                name: "MODE",
                options: [
                    ["absolute", "ABSOLUTE"],
                    ["relative", "RELATIVE"],
                ],
            },
            {
                type: "input_value",
                name: "POSITION",
                check: "Number",
                extensions: "number_validation",
            },
        ],
        previousStatement: null,
        nextStatement: null,
        colour: 355,
        tooltip: "",
        helpUrl: "",
    },
    {
        type: "set_hand_position_xyz",
        message0: "Set Hand Position at XYZ %1 %2 %3 X %4 Y %5 Z %6",
        args0: [
            {
                type: "field_dropdown",
                name: "MODE",
                options: [
                    ["absolute", "ABSOLUTE"],
                    ["relative", "RELATIVE"],
                ],
            },
            {
                type: "field_dropdown",
                name: "SIDE",
                options: [
                    ["left", "left"],
                    ["right", "right"],
                ],
            },
            {
                type: "input_dummy",
            },
            {
                type: "input_value",
                name: "X",
                check: "Number",
                align: "RIGHT",
                extensions: "number_validation",
            },
            {
                type: "input_value",
                name: "Y",
                check: "Number",
                align: "RIGHT",
                extensions: "number_validation",
            },
            {
                type: "input_value",
                name: "Z",
                check: "Number",
                align: "RIGHT",
                extensions: "number_validation",
            },
        ],
        inputsInline: false,
        previousStatement: null,
        nextStatement: null,
        colour: 355,
        tooltip: "Moves the selected hand to a target XYZ position using inverse kinematics. Left/right is from pib's own perspective: imagine standing in front of pib and looking at him (the same binding used across pib part numbering e.g. C35R/C35L).",
        helpUrl: "",
    },
]);
