# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CreateVoiceAssistantPersonality(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, description: str=None, gender: str=None, pause_threshold: float=None):  # noqa: E501
        """CreateVoiceAssistantPersonality - a model defined in Swagger

        :param name: The name of this CreateVoiceAssistantPersonality.  # noqa: E501
        :type name: str
        :param description: The description of this CreateVoiceAssistantPersonality.  # noqa: E501
        :type description: str
        :param gender: The gender of this CreateVoiceAssistantPersonality.  # noqa: E501
        :type gender: str
        :param pause_threshold: The pause_threshold of this CreateVoiceAssistantPersonality.  # noqa: E501
        :type pause_threshold: float
        """
        self.swagger_types = {
            'name': str,
            'description': str,
            'gender': str,
            'pause_threshold': float
        }

        self.attribute_map = {
            'name': 'name',
            'description': 'description',
            'gender': 'gender',
            'pause_threshold': 'pauseThreshold'
        }
        self._name = name
        self._description = description
        self._gender = gender
        self._pause_threshold = pause_threshold

    @classmethod
    def from_dict(cls, dikt) -> 'CreateVoiceAssistantPersonality':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateVoiceAssistantPersonality of this CreateVoiceAssistantPersonality.  # noqa: E501
        :rtype: CreateVoiceAssistantPersonality
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this CreateVoiceAssistantPersonality.


        :return: The name of this CreateVoiceAssistantPersonality.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this CreateVoiceAssistantPersonality.


        :param name: The name of this CreateVoiceAssistantPersonality.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this CreateVoiceAssistantPersonality.


        :return: The description of this CreateVoiceAssistantPersonality.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this CreateVoiceAssistantPersonality.


        :param description: The description of this CreateVoiceAssistantPersonality.
        :type description: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def gender(self) -> str:
        """Gets the gender of this CreateVoiceAssistantPersonality.


        :return: The gender of this CreateVoiceAssistantPersonality.
        :rtype: str
        """
        return self._gender

    @gender.setter
    def gender(self, gender: str):
        """Sets the gender of this CreateVoiceAssistantPersonality.


        :param gender: The gender of this CreateVoiceAssistantPersonality.
        :type gender: str
        """
        allowed_values = ["Male", "Female"]  # noqa: E501
        if gender not in allowed_values:
            raise ValueError(
                "Invalid value for `gender` ({0}), must be one of {1}"
                .format(gender, allowed_values)
            )

        self._gender = gender

    @property
    def pause_threshold(self) -> float:
        """Gets the pause_threshold of this CreateVoiceAssistantPersonality.


        :return: The pause_threshold of this CreateVoiceAssistantPersonality.
        :rtype: float
        """
        return self._pause_threshold

    @pause_threshold.setter
    def pause_threshold(self, pause_threshold: float):
        """Sets the pause_threshold of this CreateVoiceAssistantPersonality.


        :param pause_threshold: The pause_threshold of this CreateVoiceAssistantPersonality.
        :type pause_threshold: float
        """
        if pause_threshold is None:
            raise ValueError("Invalid value for `pause_threshold`, must not be `None`")  # noqa: E501

        self._pause_threshold = pause_threshold
