# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class GetVoiceAssistantChatMessagesMessages(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, message: str=None, timestamp: datetime=None, is_user: bool=None):  # noqa: E501
        """GetVoiceAssistantChatMessagesMessages - a model defined in Swagger

        :param message: The message of this GetVoiceAssistantChatMessagesMessages.  # noqa: E501
        :type message: str
        :param timestamp: The timestamp of this GetVoiceAssistantChatMessagesMessages.  # noqa: E501
        :type timestamp: datetime
        :param is_user: The is_user of this GetVoiceAssistantChatMessagesMessages.  # noqa: E501
        :type is_user: bool
        """
        self.swagger_types = {
            'message': str,
            'timestamp': datetime,
            'is_user': bool
        }

        self.attribute_map = {
            'message': 'message',
            'timestamp': 'timestamp',
            'is_user': 'isUser'
        }
        self._message = message
        self._timestamp = timestamp
        self._is_user = is_user

    @classmethod
    def from_dict(cls, dikt) -> 'GetVoiceAssistantChatMessagesMessages':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetVoiceAssistantChatMessages_messages of this GetVoiceAssistantChatMessagesMessages.  # noqa: E501
        :rtype: GetVoiceAssistantChatMessagesMessages
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this GetVoiceAssistantChatMessagesMessages.


        :return: The message of this GetVoiceAssistantChatMessagesMessages.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this GetVoiceAssistantChatMessagesMessages.


        :param message: The message of this GetVoiceAssistantChatMessagesMessages.
        :type message: str
        """

        self._message = message

    @property
    def timestamp(self) -> datetime:
        """Gets the timestamp of this GetVoiceAssistantChatMessagesMessages.


        :return: The timestamp of this GetVoiceAssistantChatMessagesMessages.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: datetime):
        """Sets the timestamp of this GetVoiceAssistantChatMessagesMessages.


        :param timestamp: The timestamp of this GetVoiceAssistantChatMessagesMessages.
        :type timestamp: datetime
        """

        self._timestamp = timestamp

    @property
    def is_user(self) -> bool:
        """Gets the is_user of this GetVoiceAssistantChatMessagesMessages.


        :return: The is_user of this GetVoiceAssistantChatMessagesMessages.
        :rtype: bool
        """
        return self._is_user

    @is_user.setter
    def is_user(self, is_user: bool):
        """Sets the is_user of this GetVoiceAssistantChatMessagesMessages.


        :param is_user: The is_user of this GetVoiceAssistantChatMessagesMessages.
        :type is_user: bool
        """

        self._is_user = is_user
