# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.get_voice_assistant_chat_messages_messages import GetVoiceAssistantChatMessagesMessages  # noqa: F401,E501
from swagger_server import util


class GetVoiceAssistantChatMessages(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, messages: List[GetVoiceAssistantChatMessagesMessages]=None):  # noqa: E501
        """GetVoiceAssistantChatMessages - a model defined in Swagger

        :param messages: The messages of this GetVoiceAssistantChatMessages.  # noqa: E501
        :type messages: List[GetVoiceAssistantChatMessagesMessages]
        """
        self.swagger_types = {
            'messages': List[GetVoiceAssistantChatMessagesMessages]
        }

        self.attribute_map = {
            'messages': 'messages'
        }
        self._messages = messages

    @classmethod
    def from_dict(cls, dikt) -> 'GetVoiceAssistantChatMessages':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetVoiceAssistantChatMessages of this GetVoiceAssistantChatMessages.  # noqa: E501
        :rtype: GetVoiceAssistantChatMessages
        """
        return util.deserialize_model(dikt, cls)

    @property
    def messages(self) -> List[GetVoiceAssistantChatMessagesMessages]:
        """Gets the messages of this GetVoiceAssistantChatMessages.


        :return: The messages of this GetVoiceAssistantChatMessages.
        :rtype: List[GetVoiceAssistantChatMessagesMessages]
        """
        return self._messages

    @messages.setter
    def messages(self, messages: List[GetVoiceAssistantChatMessagesMessages]):
        """Sets the messages of this GetVoiceAssistantChatMessages.


        :param messages: The messages of this GetVoiceAssistantChatMessages.
        :type messages: List[GetVoiceAssistantChatMessagesMessages]
        """

        self._messages = messages
