# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.get_all_personalities_voice_assistant_personalities import GetAllPersonalitiesVoiceAssistantPersonalities  # noqa: F401,E501
from swagger_server import util


class GetAllPersonalities(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, voice_assistant_personalities: List[GetAllPersonalitiesVoiceAssistantPersonalities]=None):  # noqa: E501
        """GetAllPersonalities - a model defined in Swagger

        :param voice_assistant_personalities: The voice_assistant_personalities of this GetAllPersonalities.  # noqa: E501
        :type voice_assistant_personalities: List[GetAllPersonalitiesVoiceAssistantPersonalities]
        """
        self.swagger_types = {
            'voice_assistant_personalities': List[GetAllPersonalitiesVoiceAssistantPersonalities]
        }

        self.attribute_map = {
            'voice_assistant_personalities': 'voiceAssistantPersonalities'
        }
        self._voice_assistant_personalities = voice_assistant_personalities

    @classmethod
    def from_dict(cls, dikt) -> 'GetAllPersonalities':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetAllPersonalities of this GetAllPersonalities.  # noqa: E501
        :rtype: GetAllPersonalities
        """
        return util.deserialize_model(dikt, cls)

    @property
    def voice_assistant_personalities(self) -> List[GetAllPersonalitiesVoiceAssistantPersonalities]:
        """Gets the voice_assistant_personalities of this GetAllPersonalities.


        :return: The voice_assistant_personalities of this GetAllPersonalities.
        :rtype: List[GetAllPersonalitiesVoiceAssistantPersonalities]
        """
        return self._voice_assistant_personalities

    @voice_assistant_personalities.setter
    def voice_assistant_personalities(self, voice_assistant_personalities: List[GetAllPersonalitiesVoiceAssistantPersonalities]):
        """Sets the voice_assistant_personalities of this GetAllPersonalities.


        :param voice_assistant_personalities: The voice_assistant_personalities of this GetAllPersonalities.
        :type voice_assistant_personalities: List[GetAllPersonalitiesVoiceAssistantPersonalities]
        """

        self._voice_assistant_personalities = voice_assistant_personalities
