# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.get_personalities_voice_assistant_personalities import GetPersonalitiesVoiceAssistantPersonalities  # noqa: F401,E501
from swagger_server import util


class GetPersonalities(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, voice_assistant_personalities: List[GetPersonalitiesVoiceAssistantPersonalities]=None):  # noqa: E501
        """GetPersonalities - a model defined in Swagger

        :param voice_assistant_personalities: The voice_assistant_personalities of this GetPersonalities.  # noqa: E501
        :type voice_assistant_personalities: List[GetPersonalitiesVoiceAssistantPersonalities]
        """
        self.swagger_types = {
            'voice_assistant_personalities': List[GetPersonalitiesVoiceAssistantPersonalities]
        }

        self.attribute_map = {
            'voice_assistant_personalities': 'voiceAssistantPersonalities'
        }
        self._voice_assistant_personalities = voice_assistant_personalities

    @classmethod
    def from_dict(cls, dikt) -> 'GetPersonalities':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetPersonalities of this GetPersonalities.  # noqa: E501
        :rtype: GetPersonalities
        """
        return util.deserialize_model(dikt, cls)

    @property
    def voice_assistant_personalities(self) -> List[GetPersonalitiesVoiceAssistantPersonalities]:
        """Gets the voice_assistant_personalities of this GetPersonalities.


        :return: The voice_assistant_personalities of this GetPersonalities.
        :rtype: List[GetPersonalitiesVoiceAssistantPersonalities]
        """
        return self._voice_assistant_personalities

    @voice_assistant_personalities.setter
    def voice_assistant_personalities(self, voice_assistant_personalities: List[GetPersonalitiesVoiceAssistantPersonalities]):
        """Sets the voice_assistant_personalities of this GetPersonalities.


        :param voice_assistant_personalities: The voice_assistant_personalities of this GetPersonalities.
        :type voice_assistant_personalities: List[GetPersonalitiesVoiceAssistantPersonalities]
        """

        self._voice_assistant_personalities = voice_assistant_personalities
