# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.get_all_chats_voice_assistant_chats import GetAllChatsVoiceAssistantChats  # noqa: F401,E501
from swagger_server import util


class GetAllChats(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, voice_assistant_chats: List[GetAllChatsVoiceAssistantChats]=None):  # noqa: E501
        """GetAllChats - a model defined in Swagger

        :param voice_assistant_chats: The voice_assistant_chats of this GetAllChats.  # noqa: E501
        :type voice_assistant_chats: List[GetAllChatsVoiceAssistantChats]
        """
        self.swagger_types = {
            'voice_assistant_chats': List[GetAllChatsVoiceAssistantChats]
        }

        self.attribute_map = {
            'voice_assistant_chats': 'voiceAssistantChats'
        }
        self._voice_assistant_chats = voice_assistant_chats

    @classmethod
    def from_dict(cls, dikt) -> 'GetAllChats':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetAllChats of this GetAllChats.  # noqa: E501
        :rtype: GetAllChats
        """
        return util.deserialize_model(dikt, cls)

    @property
    def voice_assistant_chats(self) -> List[GetAllChatsVoiceAssistantChats]:
        """Gets the voice_assistant_chats of this GetAllChats.


        :return: The voice_assistant_chats of this GetAllChats.
        :rtype: List[GetAllChatsVoiceAssistantChats]
        """
        return self._voice_assistant_chats

    @voice_assistant_chats.setter
    def voice_assistant_chats(self, voice_assistant_chats: List[GetAllChatsVoiceAssistantChats]):
        """Sets the voice_assistant_chats of this GetAllChats.


        :param voice_assistant_chats: The voice_assistant_chats of this GetAllChats.
        :type voice_assistant_chats: List[GetAllChatsVoiceAssistantChats]
        """

        self._voice_assistant_chats = voice_assistant_chats
