# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class GetVoiceAssistantChat(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, title: str=None, personality_id: str=None, personality_name: str=None):  # noqa: E501
        """GetVoiceAssistantChat - a model defined in Swagger

        :param title: The title of this GetVoiceAssistantChat.  # noqa: E501
        :type title: str
        :param personality_id: The personality_id of this GetVoiceAssistantChat.  # noqa: E501
        :type personality_id: str
        :param personality_name: The personality_name of this GetVoiceAssistantChat.  # noqa: E501
        :type personality_name: str
        """
        self.swagger_types = {
            'title': str,
            'personality_id': str,
            'personality_name': str
        }

        self.attribute_map = {
            'title': 'title',
            'personality_id': 'personality_id',
            'personality_name': 'personality_name'
        }
        self._title = title
        self._personality_id = personality_id
        self._personality_name = personality_name

    @classmethod
    def from_dict(cls, dikt) -> 'GetVoiceAssistantChat':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetVoiceAssistantChat of this GetVoiceAssistantChat.  # noqa: E501
        :rtype: GetVoiceAssistantChat
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self) -> str:
        """Gets the title of this GetVoiceAssistantChat.


        :return: The title of this GetVoiceAssistantChat.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this GetVoiceAssistantChat.


        :param title: The title of this GetVoiceAssistantChat.
        :type title: str
        """

        self._title = title

    @property
    def personality_id(self) -> str:
        """Gets the personality_id of this GetVoiceAssistantChat.


        :return: The personality_id of this GetVoiceAssistantChat.
        :rtype: str
        """
        return self._personality_id

    @personality_id.setter
    def personality_id(self, personality_id: str):
        """Sets the personality_id of this GetVoiceAssistantChat.


        :param personality_id: The personality_id of this GetVoiceAssistantChat.
        :type personality_id: str
        """

        self._personality_id = personality_id

    @property
    def personality_name(self) -> str:
        """Gets the personality_name of this GetVoiceAssistantChat.


        :return: The personality_name of this GetVoiceAssistantChat.
        :rtype: str
        """
        return self._personality_name

    @personality_name.setter
    def personality_name(self, personality_name: str):
        """Sets the personality_name of this GetVoiceAssistantChat.


        :param personality_name: The personality_name of this GetVoiceAssistantChat.
        :type personality_name: str
        """

        self._personality_name = personality_name
