# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class VoiceAssistantPersonality(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, name: str=None, description: str=None, gender: str=None, pause_threshold: float=None):  # noqa: E501
        """VoiceAssistantPersonality - a model defined in Swagger

        :param id: The id of this VoiceAssistantPersonality.  # noqa: E501
        :type id: str
        :param name: The name of this VoiceAssistantPersonality.  # noqa: E501
        :type name: str
        :param description: The description of this VoiceAssistantPersonality.  # noqa: E501
        :type description: str
        :param gender: The gender of this VoiceAssistantPersonality.  # noqa: E501
        :type gender: str
        :param pause_threshold: The pause_threshold of this VoiceAssistantPersonality.  # noqa: E501
        :type pause_threshold: float
        """
        self.swagger_types = {
            'id': str,
            'name': str,
            'description': str,
            'gender': str,
            'pause_threshold': float
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'description': 'description',
            'gender': 'gender',
            'pause_threshold': 'pauseThreshold'
        }
        self._id = id
        self._name = name
        self._description = description
        self._gender = gender
        self._pause_threshold = pause_threshold

    @classmethod
    def from_dict(cls, dikt) -> 'VoiceAssistantPersonality':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VoiceAssistantPersonality of this VoiceAssistantPersonality.  # noqa: E501
        :rtype: VoiceAssistantPersonality
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this VoiceAssistantPersonality.


        :return: The id of this VoiceAssistantPersonality.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this VoiceAssistantPersonality.


        :param id: The id of this VoiceAssistantPersonality.
        :type id: str
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this VoiceAssistantPersonality.


        :return: The name of this VoiceAssistantPersonality.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this VoiceAssistantPersonality.


        :param name: The name of this VoiceAssistantPersonality.
        :type name: str
        """

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this VoiceAssistantPersonality.


        :return: The description of this VoiceAssistantPersonality.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this VoiceAssistantPersonality.


        :param description: The description of this VoiceAssistantPersonality.
        :type description: str
        """

        self._description = description

    @property
    def gender(self) -> str:
        """Gets the gender of this VoiceAssistantPersonality.


        :return: The gender of this VoiceAssistantPersonality.
        :rtype: str
        """
        return self._gender

    @gender.setter
    def gender(self, gender: str):
        """Sets the gender of this VoiceAssistantPersonality.


        :param gender: The gender of this VoiceAssistantPersonality.
        :type gender: str
        """

        self._gender = gender

    @property
    def pause_threshold(self) -> float:
        """Gets the pause_threshold of this VoiceAssistantPersonality.


        :return: The pause_threshold of this VoiceAssistantPersonality.
        :rtype: float
        """
        return self._pause_threshold

    @pause_threshold.setter
    def pause_threshold(self, pause_threshold: float):
        """Sets the pause_threshold of this VoiceAssistantPersonality.


        :param pause_threshold: The pause_threshold of this VoiceAssistantPersonality.
        :type pause_threshold: float
        """

        self._pause_threshold = pause_threshold
