"""empty message

Revision ID: 9e48f719f042
Revises: 7a4053561c44
Create Date: 2024-05-29 12:44:40.684331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e48f719f042'
down_revision = '7a4053561c44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pose',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pose_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('pose_id')
    )
    op.create_table('motor_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('motorname', sa.String(), nullable=False),
    sa.Column('pose_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['motorname'], ['motor.name'], ),
    sa.ForeignKeyConstraint(['pose_id'], ['pose.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('motor_position')
    op.drop_table('pose')
    # ### end Alembic commands ###
