"""extend AssistantModel for visual instruction support

Revision ID: ad031de64c22
Revises: 330f7919a6f3
Create Date: 2024-04-09 09:54:31.996389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad031de64c22'
down_revision = '330f7919a6f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistant_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_image_support', sa.Boolean(), nullable=True))
    op.execute(f'UPDATE {'assistant_model'} SET {'has_image_support'} = FALSE WHERE {'has_image_support'} IS NULL')
    with op.batch_alter_table('assistant_model') as batch_op:
        batch_op.alter_column('has_image_support', nullable=False, server_default=sa.false())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistant_model', schema=None) as batch_op:
        batch_op.drop_column('has_image_support')

    # ### end Alembic commands ###
