"""add pose- and motor-position-table

Revision ID: bd36fd9780ba
Revises: 259579f4fe12
Create Date: 2024-06-20 10:16:36.985356

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bd36fd9780ba"
down_revision = "259579f4fe12"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pose",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pose_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("pose_id"),
    )

    op.create_table(
        "motor_position",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("motor_name", sa.Integer(), nullable=False),
        sa.Column("pose_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["motor_name"],
            ["motor.name"],
        ),
        sa.ForeignKeyConstraint(
            ["pose_id"],
            ["pose.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("motor_position")
    op.drop_table("pose")
    # ### end Alembic commands ###
