"""add message_history

Revision ID: c2de601304c2
Revises: 7160a4f6951f
Create Date: 2024-10-01 15:26:16.931346

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "c2de601304c2"
down_revision = "7160a4f6951f"
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("personality", schema=None) as batch_op:
        batch_op.add_column(sa.Column("message_history", sa.Integer(), nullable=True))

    conn = op.get_bind()

    conn.execute(sa.text("""
            UPDATE personality SET message_history = 10 WHERE message_history IS NULL
             """))

    with op.batch_alter_table("personality", schema=None) as batch_op:
        batch_op.alter_column("message_history", nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("personality", schema=None) as batch_op:
        batch_op.drop_column("message_history")

    # ### end Alembic commands ###
