"""add_button_programs_table

Revision ID: d4d024ef3a32
Revises: e125aa01171c
Create Date: 2026-03-17 13:53:24.716901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4d024ef3a32'
down_revision = 'e125aa01171c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('button_program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bricklet_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bricklet_id'], ['bricklet.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bricklet_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('button_program')
    # ### end Alembic commands ###
