"""change column naming

Revision ID: d5879d34c36c
Revises: ad031de64c22
Create Date: 2024-04-24 09:40:22.788970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5879d34c36c'
down_revision = 'ad031de64c22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personality', schema=None) as batch_op:
        batch_op.alter_column('assistant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        
    with op.batch_alter_table('personality') as batch_op:
        batch_op.alter_column('personalityId', new_column_name='personality_id')
        batch_op.alter_column('pauseThreshold', new_column_name='pause_threshold')

    with op.batch_alter_table('program') as batch_op:
        batch_op.alter_column('codeVisual', new_column_name='code_visual')
        batch_op.alter_column('programNumber', new_column_name='program_number')

    with op.batch_alter_table('motor') as batch_op:
        batch_op.alter_column('pulseWidthMin', new_column_name='pulse_width_min')
        batch_op.alter_column('pulseWidthMax', new_column_name='pulse_width_max')
        batch_op.alter_column('rotationRangeMin', new_column_name='rotation_range_min')
        batch_op.alter_column('rotationRangeMax', new_column_name='rotation_range_max')
        batch_op.alter_column('turnedOn', new_column_name='turned_on')

    with op.batch_alter_table('chatMessage') as batch_op:
        batch_op.alter_column('messageId', new_column_name='message_id')
        batch_op.alter_column('isUser', new_column_name='is_user')
        batch_op.alter_column('chatId', new_column_name='chat_id')

    with op.batch_alter_table('chat') as batch_op:
        batch_op.alter_column('chatId', new_column_name='chat_id')
        batch_op.alter_column('personalityId', new_column_name='personality_id')

    with op.batch_alter_table('cameraSettings') as batch_op:
        batch_op.alter_column('refreshRate', new_column_name='refresh_rate')
        batch_op.alter_column('qualityFactor', new_column_name='quality_factor')
        batch_op.alter_column('resX', new_column_name='res_x')
        batch_op.alter_column('resY', new_column_name='res_y')
 
    with op.batch_alter_table('brickletPin') as batch_op:
        batch_op.alter_column('motorId', new_column_name='motor_id')
        batch_op.alter_column('brickletId', new_column_name='bricklet_id')

    with op.batch_alter_table('bricklet') as batch_op:
        batch_op.alter_column('brickletNumber', new_column_name='brickletNumber')

    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_program_number', ['programNumber'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.drop_constraint(unique_program_number, type_='unique')

    with op.batch_alter_table('personality') as batch_op:
        batch_op.alter_column('personality_id', new_column_name='personalityId')
        batch_op.alter_column('pause_threshold', new_column_name='pauseThreshold')

    with op.batch_alter_table('program') as batch_op:
        batch_op.alter_column('code_visual', new_column_name='codeVisual')
        batch_op.alter_column('program_number', new_column_name='programNumber')

    with op.batch_alter_table('motor') as batch_op:
        batch_op.alter_column('pulse_width_min', new_column_name='pulseWidthMin')
        batch_op.alter_column('pulse_width_max', new_column_name='pulseWidthMax')
        batch_op.alter_column('rotation_range_min', new_column_name='rotationRangeMin')
        batch_op.alter_column('rotation_range_max', new_column_name='rotationRangeMax')
        batch_op.alter_column('turned_on', new_column_name='turnedOn')

    with op.batch_alter_table('chatMessage') as batch_op:
        batch_op.alter_column('message_id', new_column_name='messageId')
        batch_op.alter_column('is_user', new_column_name='isUser')
        batch_op.alter_column('chat_id', new_column_name='chatId')

    with op.batch_alter_table('chat') as batch_op:
        batch_op.alter_column('chat_id', new_column_name='chatId')
        batch_op.alter_column('personality_id', new_column_name='personalityId')

    with op.batch_alter_table('cameraSettings') as batch_op:
        batch_op.alter_column('refresh_rate', new_column_name='refreshRate')
        batch_op.alter_column('quality_factor', new_column_name='qualityFactor')
        batch_op.alter_column('res_x', new_column_name='resX')
        batch_op.alter_column('res_y', new_column_name='resY')

    with op.batch_alter_table('brickletPin') as batch_op:
        batch_op.alter_column('motor_id', new_column_name='motorId')
        batch_op.alter_column('bricklet_id', new_column_name='brickletId')

    with op.batch_alter_table('bricklet') as batch_op:
        batch_op.alter_column('bricklet_number', new_column_name='brickletNumber')

    with op.batch_alter_table('personality', schema=None) as batch_op:
        batch_op.alter_column('assistant_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
