version: '3'

services:
  cerebra:
    container_name: pib-cerebra
    image: pibrocks/cerebra
    ports: 
      - 8000:80

    environment:
      - VIRTUAL_HOST=cerebra.private.net
      - VIRTUAL_PORT=8000

  pib-backend-bridge:
    container_name: pib-backend-bridge
    image: pibrocks/pib-backend-bridge
    tty: true

    environment:
      - VIRTUAL_HOST=bridge.private.net

  pib-backend-webots:
    container_name: pib-digitaltwin-webots
    image: pibrocks/pib-digitaltwin-webots
    command: ros2 launch my_package pib_launch.py
    tty: true
    devices:
      - "/dev/dri/card0:/dev/dri/card0"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

    environment:
      - VIRTUAL_HOST=webots.private.net
      - DISPLAY=${DISPLAY}