name: CIDocker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      run: echo "$DOCKERHUB_TOKEN" | docker login --username $DOCKERHUB_USER --password-stdin

    - name: Build Docker images for AMD64 and ARM64 and push
      run: |
        docker buildx create --use
        docker buildx bake --platform linux/amd64,linux/arm64 --push .
        
